name: Bug Report
description: Create a report to notify us about any bugs.
title: "[Bug]: "
type: "Bug"
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What was the expected outcome?
      placeholder: Tell us what you see!
      value: "Description: "
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        Can you provide us with details on how to reproduce the issue?
  - type: textarea
    id: reproducing-the-bug
    attributes:
        label: Steps to reproduce the issue
        description: If you can, please describe step by step what you were doing when the bug happened 
        placeholder: Additional Context
        value: "How it happened: "
